import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProviders from "./ThemeLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Howsapp!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} newq  antialiased`}
      >
        {" "}
        <div className="hidden lg:block">
           <ThemeProviders>
          {children}
          </ThemeProviders>
        </div>
       
      </body>
      <div  className=" newq flex lg:hidden  flex-col items-center justify-center min-h-screen text-center px-4">
        <h1>
          Coming Soon for Mobile devices!
          <span className="text-blue-500"> Stay Tuned!</span>
        </h1>
      </div>
    </html>
  );
}
